server:
  port: 8001

spring:
  application:
    name:
      ms-scheduled-status
  mail:
    host: smtp.gmail.com
    port: 587
    username: <sender_mail_user>
    password: <sender_mail_password>
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
  data:
    mongodb:
      port: <port_mongo>
      host: <host_mongo>
      username: <user_mongo>
      password: <password_mongo>
      database: shalom-status
      authentication-database: admin

application:
  scheduledTimer: 15 45 13,18,19,20,21,22,23 * * ?

apis:
  ship-shalom: http://{VPS_IP}:8000/api/ship-shalom/states