server:
  port: 8001

spring:
  application:
    name: ms-scheduled-status
  redis:
    uri: <redis_uri>
    key: notification:shipping
    group: shipping_shalom
  mail:
    port: 587
    host: smtp.gmail.com
    username: <sender_mail_user>
    password: <sender_mail_password>
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
  data:
    mongodb:
      port: <port_mongo>
      host: <host_mongo>
      username: <user_mongo>
      password: <password_mongo>
      database: shalom-status
      authentication-database: admin

application:
  listenerNotificationTask: 0 */1 * * * ?
  verifyStatusTask: 0 5 8,14,15,16,17,18 * * ?

apis:
  ship-shalom: http://{VPS_IP}:8000/api/ship-shalom/states