server:
  port: 8001

spring:
  application:
    name: ms-scheduled-status
  redis-listener:
    uri: redis://<redis_password>@<host_mongo>:<redis_port>
    key: notification:shipping
    group: shipping_shalom
  data:
    mongodb:
      port: <port_mongo>
      host: <host_mongo>
      username: <user_mongo>
      password: <password_mongo>
      database: shalom-status
      authentication-database: admin

application:
  verifyStatusTask: 30 15,30,45,59 8-18 * * ?

apis:
  ship-shalom: http://{VPS_IP}:8000/api/ship-shalom/states